name: Sync Fork

permissions:
    contents: write

on:
    schedule:
        - cron: '0 0 * * *'  # 每天的午夜（UTC时间）执行
    workflow_dispatch:

jobs:
    sync_with_upstream:
        name: Sync with Upstream
        runs-on: ubuntu-latest
        if: ${{ github.event.repository.fork }}

        steps:
            - name: Checkout target repo
              uses: actions/checkout@v3
              with:
                fetch-depth: 0 
                
            - name: Sync Upstream for main
              uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
              with:
                  target_repo_token: ${{ secrets.MY_GITHUB_TOKEN }}
                  upstream_sync_repo: FongMi/Release
                  upstream_sync_branch: main
                  target_sync_branch: main
                  test_mode: false

            - name: Sync Upstream for fongmi
              uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
              with:
                  target_repo_token: ${{ secrets.MY_GITHUB_TOKEN }}
                  upstream_sync_repo: FongMi/Release
                  upstream_sync_branch: fongmi
                  target_sync_branch: fongmi
                  test_mode: false

            - name: Check for Failure
              if: failure()
              run: |
                  echo "[Error] Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork."
                  exit 1
